version: '3.7'

services:
  db:
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - 'db_data:/var/lib/postgresql/data'

  app:
    build: .
    command: bundle exec shotgun config.ru -o 0.0.0.0 -p 5000
    depends_on:
      - 'db'
    hostname: app
    ports:
      - '5000:5000'
    restart: unless-stopped
    volumes:
      - '.:/app'

volumes:
  db_data:
