version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: ${PROJECT_NAME}_web
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: [ 'sh', './docker/startup.sh' ]
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      TZ: America/Los_Angeles
    hostname: app
    image: ${PROJECT_NAME}:rubyland
    links:
      - db
    platform: linux/amd64
    ports:
      - target: ${APP_PORT}
        published: 5678
        protocol: tcp
        mode: host
    restart: unless-stopped
    volumes:
      - .:/var/app/current

  db:
    container_name: ${PROJECT_NAME}_db
    environment:
      POSTGRES_DB: ${PROJECT_NAME}_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    image: postgres:12.10
    ports:
      - target: ${DB_PORT}
        published: 5432
        protocol: tcp
        mode: host
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
