version: '3.7'

services:
  db:
    env_file:
      - '.env'
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - 'db_data:/var/lib/postgresql/data'

  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    command: bundle exec shotgun config.ru -o 0.0.0.0 -p 3000
    depends_on:
      - 'db'
    hostname: app
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - './src:/current'

volumes:
  app: # for hot-reloading
  db_data:
